Project/urls.py
from django.contrib import admin
from django.urls import path, include
from School import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prof/', include('School.urls', namespace='prof')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

School/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as view
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required



app_name = 'School'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('update/', views.update, name='update'),
    path('login/', view.LoginView.as_view(template_name='School/login.html'),name='login'),
    path('logout/', view.LogoutView.as_view(template_name='School/logout.html'), name='logout'),
    path('changepass/', view.PasswordChangeView.as_view(template_name='School/change.html'), name='change'),
    # path('api_1/', views.StudentListApiView.as_view(), name='api_1'),
    # path('api/<int:id>/', views.StudentDetailAPIView.as_view(), name='apidetail'),
    # path('update/<int:id>/', views.StudentUpdateAPIView.as_view(), name='apiupdate'),
    # path('del/<int:id>/', views.StudentDeleteAPIView.as_view(), name='del'),
    # path('create/', views.StudentCreatAPIView.as_view(),name='create'),
    path('index/', views.TemplateProfView.as_view(), name='index'),
    path('inside/', views.inside, name='inside'),
    path('page/', views.studentview, name='page'),
    path('set/', views.setsession, name='set'),
    path('get/', views.getsession, name='get'),
    path('del/', views.delsession, name='del'),
]

School/models.py
from django.db import models
from .managers import CustomManager
from ckeditor.fields import RichTextField

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    body = RichTextField()
    objects = models.Manager()

    def __str__(self):
        return self.name




# class ProxyStudent(Student):
#     students = CustomManager()
#     class Meta:
#         Proxy = True
#         ordering = ['name']





class Score(models.Model):
    result = models.PositiveIntegerField()

    def __str__(self):
        return str(self.result)

School/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from .models import Student
from ckeditor.widgets import CKEditorWidget

class UserUpdateForm(UserChangeForm):
    password = None
    # email = forms.EmailField(label='Email')
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}


class StudentForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Student
        fields = ['name','title','body']

School/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import Student
from .forms import UserUpdateForm, StudentForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.core.files.storage import FileSystemStorage
from django.db.models import Q , Avg, Min, Max, Count, Sum
# Create your views here.

def studentview(request):
    if request.method == 'POST':
        forms = StudentForm()
    else:
        forms = StudentForm()
    return render(request, 'School/page.html', {'forms':forms})


def home(request):
    students = Student.objects.all()
    return render(request, 'School/home.html', {'students':students,'data':'ahmed alaa ramadan'})

# @method_decorator(staff_member_required, name='dispatch')
class TemplateProfView(TemplateView):
    template_name = 'School/home.html'
    #
    # @method_decorator(staff_member_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

def inside(request):
    return render(request, 'base.html')



def update(request):
    if request.method == 'POST':
        forms = UserUpdateForm(request.POST, instance=request.user)
        if forms.is_valid():
            forms.save()
            return HttpResponse('<h1>Successful Update User</h1>')
    else:
        forms = UserUpdateForm(instance=request.user)
    return render(request, 'School/update.html', {'forms':forms})





#
# from rest_framework.generics import ListAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView
# from rest_framework.generics import CreateAPIView
# from .serializers import StudentSerializer
#
# class StudentCreatAPIView(CreateAPIView):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer
#
#
#
# class StudentListApiView(ListAPIView):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer
#
# class StudentDetailAPIView(RetrieveAPIView):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer
#     lookup_field = 'id'
#
#
# class StudentUpdateAPIView(UpdateAPIView):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer
#     lookup_field = 'id'
#
#
# class StudentDeleteAPIView(DestroyAPIView):
#     queryset = Student.objects.all()
#     serializer_class = StudentSerializer
#     lookup_field = 'id'


def setsession(request):
    request.session['name'] = 'Ahmed'
    return render(request, 'School/set.html')

def getsession(request):
    if 'name' in request.session:
        name = request.session['name']
        request.session.modified = True
        return render(request, 'School/get.html', {'name':name})
    else:
        return HttpResponse('request session Expires')


def delsession(request):
    request.session.flush()
    return render(request, 'School/del.html')

School/templates/School/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="ChangePass">
</form>
</body>
</html>

School/templates/School/del.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Del Session</title>
</head>
<body>
<h1>Del Session........!!!!</h1>
</body>
</html>

School/templates/School/get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get Session</title>
</head>
<body>
<h1>Get Session ........!!!!!</h1>
<h1>
    {{name}}<hr>
    {{request.session.get_session_cookie_age}}<br>
    {{request.session.get_expiry_age}}<br>
    {{request.session.get_expiry_date}}
</h1>
</body>
</html>

School/templates/School/home.html
<!DOCTYPE html>
{% load static %}
{% load my_templatetag %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

    <link href="{% static 'School/css/main.css' %}" rel="stylesheet"/>

</head>
<body class="body">
<h4>Ahmed Alaa</h4>
<p onclick="btn();">Abdo Alaa Ramadan</p>
<h1>
    {% for student in students %}
        {{student.name}}<br>
        {{student.title}}<br>
        {{student.body}}<hr>
    {% endfor %}
</h1>
<h3>
    {{data|upper}}
    {{data|cut:5}}
</h3>
<h1>
    <a href="/prof/login" class="btn btn-primary">Login</a>
    <a href="/prof/logout" class="btn btn-warning">Logout</a>
</h1>
<img src="{% static 'images/img.jpg' %}" alt="no found" draggable="false">
<img src="{% get_static_prefix %}images/img.jpg" alt="no found">
<a href="/static/images/img.jpg">Load Image</a>
<img src="{% static 'School/images/img.jpg' %}" alt="django">
<img src="{% get_static_prefix %}School/images/img.jpg" align="django">
<a href="/static/School/images/img.jpg">Load School Image</a>


<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>




<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

<script src="{% static 'School/js/main.js' %}"></script>


</body>
</html>

School/templates/School/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login"/>
    </form>
</h1>
</body>
</html>

School/templates/School/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>
<h3>Logout Success....</h3>
<h1><a href="{% url 'prof:login' %}">Login</a></h1>

</body>
</html>

School/templates/School/page.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page . html</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

    <link href="{% static 'School/css/main.css' %}" rel="stylesheet"/>
</head>
<body>
<h1>
    <form method="post">
        {% csrf_token %}
        {{forms.media}}
        {% bootstrap_form forms %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

</h1>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

<script src="{% static 'School/js/main.js' %}"></script>
</body>
</html>

School/templates/School/set.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Set Session</title>
</head>
<body>
<h1>Set Session..........!!!!</h1>
</body>
</html>

School/templates/School/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update USer</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit" value="Update">
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Template out side projec</title>
</head>
<body>
<h1>template out side</h1>
</body>
</html>